version: smartide/v0.3
orchestrator:
  type: docker-compose
  version: 3
workspace:
  dev-container:
    service-name: smartide-template-dotnet-v2-vscode-dapr
    ports:
      tools-webide-vscode: 6800
      tools-ssh: 6822
      apps-emailClient: 4000
      apps-virtualSimulator: 5000
      apps-messageQueueService: 9001
    ide-type: vscode
    volumes: 
        git-config: true
        ssh-key: true
    command:
  services:
    smartide-template-dotnet-v2-vscode-dapr:
      image: registry.cn-hangzhou.aliyuncs.com/smartide/smartide-dotnet-v2-vmlc
      restart: always
      runtime: sysbox-runc
      hostname: dev-conatiner
      environment:
        ROOT_PASSWORD: root123
        LOCAL_USER_PASSWORD: root123
      ports:
        - 6822:22
        - 6800:3000
        - 4000:4000
        - 5000:5000
        - 9001:9001
      volumes:
        - .:/home/project
      networks:
        - smartide-network  
  networks:
    smartide-network:
      external: true      
